import { basePath, concerts, contactEmail, facebookUrl, facts, nav, news, partners, repertoire, sections, ticketUrl } from "./data/site.mjs";
const fmt = (d, opts={weekday:"long",day:"numeric",month:"long",year:"numeric"}) => new Intl.DateTimeFormat("nb-NO", opts).format(new Date(d));
const icon = "♪";
const esc = (s)=>String(s).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const sitePath = (path) => `${basePath}${path}`;
const localHref = (href) => href.startsWith("/") ? sitePath(href) : href;
const mailtoHref = `mailto:${contactEmail}`;
const link = (href,label)=>`<a href="${localHref(href)}">${label}</a>`;
function shell(title, desc, body){return `<!doctype html><html lang="nb"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | Asker Symfoniorkester</title><meta name="description" content="${desc}"><meta property="og:title" content="${title} | Asker Symfoniorkester"><meta property="og:description" content="${desc}"><meta property="og:type" content="website"><link rel="icon" href="${sitePath("/favicon.svg")}"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Inter:wght@400;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="${sitePath("/styles.css")}"></head><body><header class="header"><nav class="wrap nav" aria-label="Hovednavigasjon"><a class="brand" href="${sitePath("/")}"><span class="mark">${icon}</span><span class="serif" style="font-size:22px;font-weight:700">Asker Symfoniorkester</span></a><div class="links">${nav.map(([l,h])=>link(h,l)).join("")}</div><a class="btn" href="${ticketUrl}">Billetter</a></nav></header><main>${body}</main>${footer()}</body></html>`}
function footer(){return `<footer class="footer"><div class="wrap footer-grid"><div><div class="brand"><span class="mark">${icon}</span><span class="serif" style="font-size:28px;font-weight:700">Asker Symfoniorkester</span></div><p class="lead" style="font-size:16px">Klassisk musikk, fellesskap og spilleglede siden 1972. Et ambisiøst amatørorkester med lokal forankring i Asker.</p></div><div><p class="eyebrow">Lenker</p>${nav.slice(0,6).map(([l,h])=>`<p>${link(h,l)}</p>`).join("")}</div><div><p class="eyebrow">Kontakt</p><p>${contactEmail}</p><p>Asker, Norge</p><p><a href="${facebookUrl}">Facebook</a></p></div><div class="card"><p class="eyebrow">Støtt oss</p><h2 class="serif">Grasrotandelen</h2><p>Velg Asker Symfoniorkester hos Norsk Tipping.</p><a class="btn" href="${sitePath("/stott-oss/")}">Les mer</a></div></div></footer>`}
function hero(eyebrow,title,text){return `<section class="hero visual"><div class="orb"></div><div class="wrap"><p class="eyebrow">${eyebrow}</p><h1 class="hero-title">${title}</h1><p class="lead">${text}</p></div></section>`}
function intro(e,t,x=""){return `<div class="intro"><p class="eyebrow">${e}</p><h2 class="display">${t}</h2>${x?`<p class="lead">${x}</p>`:""}</div>`}
function concertCard(c,featured=true){return `<article class="concert glass ${featured?"featured":""}"><div class="concert-art visual staff"><span class="pill">${c.type}</span><div><p>${c.venue}</p><h2>${c.title}</h2></div></div><div class="concert-body"><div class="meta"><span>${fmt(c.date)}</span><span>kl. ${c.time}</span><span>${c.venue}</span></div><p class="lead" style="font-size:18px">${c.desc}</p><p class="eyebrow">Program</p><ul class="list">${c.programme.map(w=>`<li>${esc(w)}</li>`).join("")}</ul><p><a class="btn" href="${ticketUrl}">Billetter</a> <a class="btn secondary" href="${sitePath(`/konserter/${c.slug}/`)}">Les mer</a></p></div></article>`}
function facebook(){const href=encodeURIComponent(facebookUrl);return `<section class="fb glass" style="border-radius:34px;padding:18px"><p class="eyebrow">Facebook</p><h2 class="serif" style="font-size:42px;margin:0 0 16px">Siste fra orkesteret</h2><iframe title="Asker Symfoniorkester Facebook feed" src="https://www.facebook.com/plugins/page.php?href=${href}&tabs=timeline&width=500&height=560&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=false" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"></iframe><p><a href="${facebookUrl}">Åpne Facebook-siden</a></p></section>`}
export function pages(){const out=[];out.push(["/",shell("Hjem","Klassisk musikk, fellesskap og spilleglede siden 1972.",`<section class="hero visual"><div class="orb"></div><div class="wrap grid"><div><p class="eyebrow">Asker • siden 1972</p><h1 class="hero-title">Asker Symfoniorkester</h1><p class="lead">Klassisk musikk, fellesskap og spilleglede siden 1972. Et ambisiøst amatørorkester med varme konsertopplevelser i Asker og omegn.</p><p><a class="btn" href="#neste-konsert">Se neste konsert</a> <a class="btn secondary" href="${sitePath("/bli-med/")}">Bli med i orkesteret</a></p></div><div class="photo glass visual"><div class="photo-inner staff"></div></div></div></section><section id="neste-konsert" class="wrap section">${intro("Neste konsert","Unge solister, sommerlys og klassiske favoritter","Neste prosjekt samler Asker Symfoniorkester og solister fra Asker kulturskole i Østenstad kirke.")}${concertCard(concerts[0])}</section><section class="wrap section grid2"><div>${intro("Om orkesteret","Ambisiøst amatørorkester med hjerte for Asker","Asker Symfoniorkester samler engasjerte amatørmusikere fra Asker og omegn til symfoniske konsertopplevelser.")}<div class="stats">${facts.map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join("")}</div></div><div class="grid2">${["Konserter","Fellesskap","Repertoar","Rekruttering"].map(t=>`<div class="card"><p class="eyebrow">${t}</p><h3>${t}</h3><p class="list">Premium kulturprofil, tydelig informasjon og varmt lokalt fellesskap.</p></div>`).join("")}</div></section><section class="wrap section grid2"><div>${intro("Aktuelt","Nytt fra orkesteret")}${news.map(([t,d,x])=>`<article class="card"><p class="eyebrow">${d}</p><h3>${t}</h3><p class="list">${x}</p></article>`).join("")}</div>${facebook()}</section><section class="wrap section"><div class="cta"><h2 class="display">Støtt musikken i lokalmiljøet</h2><p class="lead">Din støtte bidrar til noter, lokaler, solister, unge musikere og åpne konsertopplevelser i Asker.</p><a class="btn" href="${sitePath("/stott-oss/")}">Støtt oss</a></div></section>`)]);
out.push(["/konserter/",shell("Konserter","Kommende konserter for Asker Symfoniorkester.",hero("Konserter","Kommende konsertopplevelser","Utforsk sesongens konserter, program, solister og praktisk informasjon.")+`<section class="wrap section cards">${concerts.map(c=>concertCard(c)).join("")}</section>`)]);
for(const c of concerts){out.push([`/konserter/${c.slug}/`,shell(c.title,c.desc,hero(c.type,c.title,c.desc)+`<section class="wrap section grid2"><article class="glass" style="border-radius:34px;padding:34px"><h2 class="display">Program</h2><ul class="list">${c.programme.map(w=>`<li>${esc(w)}</li>`).join("")}</ul><h2 class="serif" style="font-size:46px">Solister</h2><ul class="list">${c.soloists.map(s=>`<li>${esc(s)}</li>`).join("")}</ul></article><aside class="card"><p class="eyebrow">Praktisk informasjon</p><h2 class="serif">${fmt(c.date)}</h2><p>kl. ${c.time}<br>${c.venue}<br>Dirigent: ${c.conductor}</p><a class="btn" href="${ticketUrl}">Kjøp billett</a><button class="btn secondary">Del konsert</button></aside></section>`)]);}
out.push(["/sesongen/",simple("Sesongen 2026/27","En sesong med nærhet, klang og oppdagelser",`<div class="grid2">${["Velkommen til en ny sesong","Høydepunkter","For familier og nye lyttere","Lokalt kulturliv i Asker"].map(t=>`<article class="card"><h3>${t}</h3><p class="list">Konserter som oppleves både høytidelige og åpne, med musikalsk kvalitet og lokal tilhørighet.</p></article>`).join("")}</div><div class="timeline">${concerts.map(c=>`<div class="timeline-row"><span>${fmt(c.date,{day:"numeric",month:"long",year:"numeric"})}</span><strong>${c.title}</strong><span>${c.venue}</span></div>`).join("")}</div>`)])
out.push(["/om-oss/",simple("Om orkesteret","Et levende symfoniorkester i Asker siden 1972",`${intro("Historie og identitet","Spilleglede med symfoniske ambisjoner","Siden 1972 har orkesteret gitt amatørmusikere en arena for å utvikle seg, spille stort repertoar og skape konserter for lokalmiljøet.")}<div class="stats">${facts.map(([v,l])=>`<div class="stat"><strong>${v}</strong><span>${l}</span></div>`).join("")}</div><article class="card"><p class="eyebrow">Dirigent</p><h3>Carl Nilsen</h3><p class="list">Dirigenten leder orkesterets musikalske arbeid og skaper trygge rammer for ambisiøst amatørmusikalsk samspill.</p></article>`)])
out.push(["/musikere/",simple("Musikere","Orkesterets stemmer",`<div class="grid3">${sections.map(s=>`<article class="card"><p class="eyebrow">Instrumentgruppe</p><h3>${s}</h3><p class="list">Navn kommer<br>Navn kommer<br>Navn kommer</p></article>`).join("")}</div><div class="cta"><h2 class="display">Spiller du et orkesterinstrument?</h2><a class="btn" href="${sitePath("/bli-med/")}">Kontakt oss</a></div>`)])
out.push(["/bli-med/",simple("Bli med","Finn plass i orkesterklangen",joinForm("Send oss en melding"))])
out.push(["/repertoar/",simple("Repertoar","Fra nordiske klanger til klassiske hovedverk",`<div class="grid4">${repertoire.map(r=>`<article class="card"><p class="eyebrow">Repertoar</p><h3>${r}</h3><p class="list">Programdetaljer og tidligere verk kan legges inn her.</p></article>`).join("")}</div>`)])
out.push(["/medlemmer/",simple("For medlemmer","Praktisk informasjon for orkesteret",`<div class="grid2"><article class="card"><h3>Prøveplan</h3><p class="list">Tirsdag 18. august: Første prøve<br>Tirsdag 1. september: Gruppeprøver<br>Helgeseminar: dato annonseres<br>Generalprøve: uken før konsert</p></article>${["Praktisk informasjon","Noter","Oppmøtetider","Meldinger fra dirigent og styre"].map(t=>`<article class="card"><h3>${t}</h3><p class="list">Plassholder for oppdatert intern informasjon.</p></article>`).join("")}</div>`)])
out.push(["/stott-oss/",simple("Støtt oss","Hjelp oss å skape levende orkestermusikk i Asker",`<div class="grid2"><article class="glass" style="border-radius:34px;padding:34px"><p class="eyebrow">Grasrotandelen</p><h2 class="display">Velg oss hos Norsk Tipping</h2><p class="lead">Gjennom Grasrotandelen kan du støtte Asker Symfoniorkester uten ekstra kostnad.</p></article><div class="grid2">${["Noter og leie av verk","Konsertlokaler","Solister og unge musikere","Lokale samarbeidsprosjekter"].map(x=>`<div class="card">${x}</div>`).join("")}</div></div><div class="grid4">${partners.map(p=>`<div class="logo-box">${p}</div>`).join("")}</div>`)])
out.push(["/aktuelt/",simple("Aktuelt","Nyheter, prosjekter og meldinger",`<div class="grid2"><div>${news.map(([t,d,x])=>`<article class="card"><p class="eyebrow">${d}</p><h3>${t}</h3><p class="list">${x}</p></article>`).join("")}</div>${facebook()}</div>`)])
out.push(["/kontakt/",simple("Kontakt","Ta kontakt med orkesteret",joinForm("Kontaktskjema")+`<div class="card"><h3>Kontaktpunkter</h3><p class="list">Generell kontakt: ${contactEmail}<br>Rekruttering: ${contactEmail}<br>Facebook: <a href="${facebookUrl}">åpne side</a><br>Kart/venue-plassholder: Asker og omegn</p></div>`)])
return out;}
function simple(title,heading,content){return shell(title,heading,hero(title,heading,"Asker Symfoniorkester samler engasjerte amatørmusikere fra Asker og omegn til musikalske opplevelser med kvalitet og lokal tilhørighet.")+`<section class="wrap section">${content}</section>`) }
function joinForm(title){return `<div class="grid2"><div>${intro("Rekruttering","Et varmt og ambisiøst fellesskap","Vi ønsker dyktige amatørmusikere, studenter, tidligere profesjonelle og voksne som vil tilbake til musikken velkommen.")}${["Hvem ser vi etter?","Hvordan foregår en prøve?","Hva forventes?"].map(t=>`<article class="card"><h3>${t}</h3><p class="list">Du bør beherske instrumentet godt, møte forberedt og ønske å bidra sosialt og musikalsk.</p></article>`).join("")}</div><form class="form glass" style="border-radius:34px;padding:34px" action="${mailtoHref}" method="post" enctype="text/plain"><h2 class="display">${title}</h2><label>Navn<input></label><label>Instrument / tema<input></label><label>E-post<input></label><label>Melding<textarea rows="7"></textarea></label><button type="submit" class="btn">Send melding</button><p class="form-note">Skjemaet åpner e-postprogrammet ditt. Du kan også skrive direkte til <a href="${mailtoHref}">${contactEmail}</a>.</p></form></div>`}
